server:
  port: 8081
    
spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
        trace: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:inyeccionsql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: null
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
logging:
  pattern:
    console: '%-5level %logger : %msg%n'
        